/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj.util.Color;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSubsystem extends SubsystemBase {

    public enum LightStatus {
        OFF, WHITE, RED, GREEN
    }

    private LightStatus m_LightStatus = LightStatus.RED;
    
    private final CANBus kCANBus = new CANBus("rio");
    private final CANdle m_FrontCandle = new CANdle(50, kCANBus);
    private final CANdle m_RearCandle = new CANdle(51, kCANBus);

    RGBWColor kGreen = new RGBWColor(0, 217, 0, 0);
    RGBWColor kRed = new RGBWColor(217, 0, 0, 0);
    RGBWColor kWhite = new RGBWColor(Color.kWhite).scaleBrightness(1);

    private final ColorFlowAnimation m_slot0Animation = new ColorFlowAnimation(0, 8)
        .withSlot(0)
        .withColor(new RGBWColor(45, 26, 246, 0))
        .withDirection(AnimationDirectionValue.Forward)
        .withFrameRate(Hertz.of(25));

    private final SolidColor[] m_colors = new SolidColor[] {
    };

    public LEDSubsystem() {

        m_FrontCandle.setControl(new SolidColor(0, 32).withColor(kWhite));
        m_RearCandle.setControl(new SolidColor(0, 32).withColor(kWhite));
        m_LightStatus = LightStatus.WHITE;

       // setDefaultCommand(updateLEDs());
    }

    public void setRed()
    {
        if(m_LightStatus == LightStatus.RED)
            return;

        m_FrontCandle.setControl(new SolidColor(0, 32).withColor(kRed));
        m_RearCandle.setControl(new SolidColor(0, 32).withColor(kRed));
        m_LightStatus = LightStatus.RED;
    }
    public void setGreen()
    {
        if(m_LightStatus == LightStatus.GREEN)
            return;

        m_FrontCandle.setControl(new SolidColor(0, 32).withColor(kGreen));
        m_RearCandle.setControl(new SolidColor(0, 32).withColor(kGreen));
    }
    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_FrontCandle.setControl(solidColor);
                m_RearCandle.setControl(solidColor);
            }
            m_FrontCandle.setControl(m_slot0Animation);
            m_RearCandle.setControl(m_slot0Animation);
        });
    }
}
